Autosplit and more
mapsme/borders pull request #7
Opened 2020-10-16 16:20 UTC by alexey-zakharenkov

This PR makes major changes to the application that makes it incompatible with the older version

- It has been adopted to run in docker containers
- Python code was migrated to python3
- Database structure was changed
- Automatic splitting a region into parts based on a ML mwm size estimation model was introduced
- Many other fixes and improvements

2020-10-19 09:00 UTC, jbenua requested changes

2020-10-19 09:00 UTC, jbenua commented on db/Dockerfile.db
> +##git clone https://github.com/mapsme/borders.git mapsme_borders
это ненужная строка?

2020-10-19 09:00 UTC, jbenua commented on db/create_osm_places_table.sql
> +select count(*) from osm_places where g_type='point' and population is null;
неконсистентное форматирование sql, давай везде одинаково?

2020-10-19 09:00 UTC, jbenua commented on db/tiles2pg.py
> +            m = re.match(r'^\s*(\d+)\s+(-?\d+)\s+(-?\d+)', line)
предлагаю вынести регулярку в константы и дать ей какое-нибудь имя

2020-10-19 09:00 UTC, jbenua commented on db/tiles2pg.py
> +                               )
отступы неконсистентны

2020-10-19 09:00 UTC, jbenua commented on db/tiles2pg.py
> +                print(line)
может лучше лог?

2020-10-19 09:00 UTC, jbenua commented on db/tiles2pg.py
> +options = parser.parse_args()
предлагаю это завернуть в 
```python
if __name__ == "__main__":
    ...
```

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +from collections import defaultdict
это лучше повыше (в самое начало, системная либа), а вот посгрю на эту строку

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +            ),
мне кажется, простой list comprehension с условием здесь выглядел бы органичнее

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +    def mark_cluster_finished(self, cluster_id):
используется всего в одном месте в этом пр и занимает на 3 строки больше, чем если не выносить в отдельный метод. попахивает тимофеем:)

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +    def get_cluster_count(self):
аналогично, используется всего в одном месте в этом пр и занимает на 3 строки больше, чем если не выносить в отдельный метод

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +                                  common_border_matrix):
какая-то неконсистентность в аргументах. надо либо dcu в конец поставить, либо всем ассайнить типы

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +    common_borders = defaultdict(lambda: 0.0)  # cluster representative => common border length
```defaultdict(float)```?

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +                dcu.clusters[small_cluster_id]['mwm_size_est'] +
предлагаю расставить скобки для большей прозрачности

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +            common_borders[cluster_id]/total_common_border_length
пробелы вокруг `/`

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +        ) if total_adjacent_mwm_size_est else
как-то очень развесисто, предлагаю либо в отдельный метод `get_choice_criterion`, либо обычный if

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +    FOLDER='split_results'
в константы наверх?

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +    FOLDER='split_results'
ну и если это для дебага, то можно в отдельное файло выкусить

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +            '{{{','.join(str(x) for x in subregion_ids)}}}',
уф, слишком много кавычек и скобочек. мб сформируем этот аргумент до запроса?

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +            AND b1.osm_id NOT IN (-9086712)  -- crunch, stub to exclude incorrect subregions
в константы этот айдишник? с комментом, что это за регион

2020-10-19 09:00 UTC, jbenua commented on web/app/auto_split.py
> +        print(f"Many countries for region '{region_name}' id={region_id}")
лог? ну и из текста не очень понятно, что произошло, ну many и many. too many мб?

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    return bool(cur.rowcount > 0)
bool можно убрать

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    return bool(cur.rowcount > 0)
можно заменить на ```count(dictinct osmid)``` и не таскать туда-сюда из базы кучу данных

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +        SELECT 1
тоже можно сократить до ```select count(..)```

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    if is_admin:
is_admin_region? я прочитала это как "если пользователь админ, ..."

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    xml = xml + '</osm>'
предлагаю создание xml в отдельный метод бахнуть

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    return '"{}"'.format(value)
мб тут какой-нибудь цикл сделать, или reduce?

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    #return json.dumps(refs)
не используется?

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    if y is not None:
а если None?

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +def import_osm():
ооочень большой метод, предлагаю распилить

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    return outer[0] <= inner[0] and outer[1] <= inner[1] and outer[2] >= inner[2] and outer[3] >= inner[3]
предлагаю отформатировать и уместить в 79 символов:)

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +        for res in cur:
предлагаю ```(name, outer, min_area, inner, coords) in cur:```

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +    xml = xml + '</osm>'
аналогично, предлагаю выделить

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-10-19 09:00 UTC, jbenua commented on web/app/borders_api.py
> +#!/usr/bin/python3.6
предлагаю этот огромный файл разрезать на несколько, например api + utils

2020-10-20 04:08 UTC, rostixman approved these changes

2020-10-30 09:46 UTC, alexey-zakharenkov commented
@jbenua я вроде учёл все замечания. Посмотри всё снова, пожалуйста.

2020-11-16 09:31 UTC, jbenua requested changes

2020-11-16 09:31 UTC, jbenua commented on db/tiles2pg.py
> +    COUNT_LAT_LON_RE = r'^\s*(\d+)\s+(-?\d+)\s+(-?\d+)'
я люблю именованные группы, их и доставать потом можно более явно
но не настаиваю

2020-11-16 09:31 UTC, jbenua commented on db/tiles2pg.py
> +                        ''', (count, lon, lat, lon + 0.01, lat + 0.01)
а почему именно такой сдвиг? давай это вынесем в константы с понятным именем и мб комментарием, зачем это вообще

2020-11-16 09:31 UTC, jbenua commented on web/app/auto_split.py
> +              ({get_union_sql(subregion_ids[1: ])})
лишний пробел после `:`

2020-11-16 09:31 UTC, jbenua commented on web/app/auto_split.py
> +    cursor = conn.cursor()
лучше `with conn.cursor()...`

2020-11-16 09:31 UTC, jbenua commented on web/app/auto_split_debug.py
> +    cursor = conn.cursor()
`with conn.cursor()...`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +
\+ строка

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +app.debug=config.DEBUG
форматирование продолбалось?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    xmin = float(request.args.get('xmin'))
а если это не `float`? мб валидации добавить?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    xmin = request.args.get('xmin')
а тут не важно, `float` это или нет?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +        cur = g.conn.cursor()
`with cursor()..:`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with ..cursor()..:`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    region_id1 = int(request.args.get('id1'))
валидация данных?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()...:`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    for rec in cur:
предлагаю тут распаковать сразу по именам:
```python
for (id, name, admin_level, area) in cur:
   ...
```

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api_utils.py
> +def assign_region_to_lowest_parent(region_id):
что есть lowest parent?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    region_id = int(request.args.get('id'))
валидация?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +            return jsonify(status="Could not use 'apply to similar' for non-administrative regions")
чот слишком длинно, 79 по PEP

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +            divide_into_clusters_preview if preview else
лучше в 3 строки и условие на отдельной

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    if config.READONLY:
предлагаю это вынести в какой-нибудь декоратор, больно часто встречается

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    for res in cur:
предлагаю распаковать по переменным сразу

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cursor = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +            divide_into_subregions_preview if preview else
и тут в 3 строки

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    lat = request.args.get('lat')
валидация?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cursor = g.conn.cursor()
`with g.conn.cursor()...:`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    region_id = int(request.args.get('id'))
валидация?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cursor = g.conn.cursor()
`with g.conn.cursor()..:`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    region_id = int(request.args.get('id'))
валидация?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    table = config.TABLE
предлагаю дать этой таблице чуть более говорящее имя переменной

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()..:`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    for rec in cur:
предлагаю распаковать в тупль переменных сразу

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +        """, (xmin, ymin, xmax, ymax, config.SMALL_KM2 * 1000000)
магическое число в константы наверх

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with ..cursor()...`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()...`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    if table in config.OTHER_TABLES:
```python
table = config.OTHER_TABLES.get(table, config.TABLE)
```

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    region_id = int(request.args.get('id'))
валидация

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cursor = g.conn.cursor()
`with g.conn.cursor()...`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    xmin = request.args.get('xmin')
валидация?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    if table in config.OTHER_TABLES:
тоже уже не в первый раз вижу. вынесем в отдельный метод?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +                f"geom && ST_MakeBox2D(ST_Point({xmin}, {ymin}),"
тоже уже не в первый раз вижу. вынесем в отдельный метод?

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cur = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/borders_api.py
> +    cursor = g.conn.cursor()
`with g.conn.cursor()`

2020-11-16 09:31 UTC, jbenua commented on web/app/countries_structure.py
> +unilevel_countries = {
я бы константы вынесла в отдельный файл

2020-11-16 09:31 UTC, jbenua commented on web/app/data/prediction_model.py
> +        print("C", C_array)
а почему не `logging`

2020-11-16 09:31 UTC, jbenua commented on web/app/osm_xml.py
> +
мож тут lxml или bs4 заюзать?

2020-11-24 08:45 UTC, alexey-zakharenkov commented on db/tiles2pg.py
> +    COUNT_LAT_LON_RE = r'^\s*(\d+)\s+(-?\d+)\s+(-?\d+)'
Избавился от регулярок, делаю обычный ' '.split()

2020-11-24 08:46 UTC, alexey-zakharenkov commented on db/tiles2pg.py
> +                        ''', (count, lon, lat, lon + 0.01, lat + 0.01)
Добавил константу и поясняющий комментарий

2020-11-24 08:47 UTC, alexey-zakharenkov commented on web/app/auto_split.py
> +    cursor = conn.cursor()
Сделал контекстный менеджер для курсоров кмк везде

2020-11-24 08:49 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +    xmin = float(request.args.get('xmin'))
Добавил валидацию параметров, приходящих в серверные апишные методы, в виде декоратора validate_args_types в файле borders_api.py.

2020-11-24 08:51 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +    xmin = request.args.get('xmin')
Теперь после валидации в дектораторе validate_args_types гарантируется, что это float, иначе ещё до этой строчки в клиент вернётся ошибка.

2020-11-24 08:51 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +    for rec in cur:
ок, сделал здесь и ещё в нескольких местах

2020-11-24 08:52 UTC, alexey-zakharenkov commented on web/app/borders_api_utils.py
> +def assign_region_to_lowest_parent(region_id):
дал док-стринг с пояснением

2020-11-24 08:52 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +    if config.READONLY:
сделал декоратор check_write_access

2020-11-24 08:52 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +    for res in cur:
+

2020-11-24 08:53 UTC, alexey-zakharenkov commented on web/app/countries_structure.py
> +unilevel_countries = {
+, файл countries_division.py

2020-11-24 08:57 UTC, alexey-zakharenkov commented on web/app/data/prediction_model.py
> +        print("C", C_array)
Тут подразумевается, что обучение и тюнинг предсказательной модели происходит в ручном контролируемом режиме, очень вероятно в REPL.

2020-11-24 08:59 UTC, alexey-zakharenkov commented on web/app/osm_xml.py
> +
Это унаследованный код, который, тьфу-тьфу-тьфу, нормально работает. Может как-нибудь в следующий раз?

2020-11-24 09:00 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +            divide_into_subregions_preview if preview else
ок

2020-11-24 09:01 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +    table = config.TABLE
переименовал везде table на borders_table, в том числе конфигурационный параметр config.TABLE => config.BORDERS_TABLE

2020-11-24 09:03 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +        """, (xmin, ymin, xmax, ymax, config.SMALL_KM2 * 1000000)
Магическое число ушло в SQL в виде 10e6. Перевод метров в километры, думаешь, нужна константа?

2020-11-24 09:04 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +    if table in config.OTHER_TABLES:
Переделал во всех 4 местах

2020-11-24 09:09 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +                f"geom && ST_MakeBox2D(ST_Point({xmin}, {ymin}),"
ок. Функция geom_intersects_bbox_sql

2020-11-24 11:11 UTC, jbenua commented on web/app/osm_xml.py
> +
хаххаха, хорошо:)

2020-11-24 14:23 UTC, jbenua requested changes

2020-11-24 14:23 UTC, jbenua commented on web/app/templates/index.html
> +                        <option value="country">стране</option>
форматтером бы, да по этому файлу

2020-11-24 14:23 UTC, jbenua commented on web/app/static/borders.js
> +var STYLE_BORDER = { stroke: true, color: '#03f', weight: 3, fill: true, fillOpacity: 0.1 };
реквестирую форматтер на этот файл

2020-11-24 14:23 UTC, jbenua commented on web/app/static/borders.js
> +		url: 'http://127.0.0.1:8111/import?' + encodeURI(params_str),
тут точно не надо из конфига или откуда-нибудь еще брать?

2020-12-01 09:24 UTC, alexey-zakharenkov commented on web/app/static/borders.js
> +var STYLE_BORDER = { stroke: true, color: '#03f', weight: 3, fill: true, fillOpacity: 0.1 };
Пропустил через форматтер все html и js-файлы в директориях web/app/{static,templates}

2020-12-01 09:28 UTC, alexey-zakharenkov commented on web/app/static/borders.js
> +		url: 'http://127.0.0.1:8111/import?' + encodeURI(params_str),
Вынес путь http://127.0.0.1:8111/import в файл config.js.

По сценарию использования, при работе в этом веб-приложении есть возможность выгрузить часть карты в редактор JOSM, который запущен на клиентской машине, так что IP без хитрых переназначений портов будет всегда такой. А порт не будет меняться по заверениям самих разработчиков редактора JOSM (именно в силу сценария использования, чтобы внешние приложения всегда могли полагаться на один и тот же порт).

2020-12-08 12:55 UTC, alexey-zakharenkov commented on web/app/templates/index.html
> +                        <option value="country">стране</option>
done

2020-12-08 12:56 UTC, alexey-zakharenkov commented on db/Dockerfile.db
> +##git clone https://github.com/mapsme/borders.git mapsme_borders
да, удалил

2020-12-08 12:58 UTC, alexey-zakharenkov commented on db/create_osm_places_table.sql
> +select count(*) from osm_places where g_type='point' and population is null;
done

2020-12-08 13:01 UTC, alexey-zakharenkov commented on db/tiles2pg.py
> +            m = re.match(r'^\s*(\d+)\s+(-?\d+)\s+(-?\d+)', line)
избавился тут от регулярки, заменив на str.split() c проверкой преобразования выделенных групп к int.

2020-12-08 13:01 UTC, jbenua approved these changes

2020-12-08 13:01 UTC, jbenua commented on web/app/static/borders.js
> +var pMarker = L.marker([0, 0], {
я бы переменьки наверх вынесла, но это минорно

2020-12-08 13:02 UTC, alexey-zakharenkov commented on db/tiles2pg.py
> +                               )
а сейчас?

2020-12-08 13:08 UTC, merged