Improve sustainability
mapsme/borders pull request #8
Opened 2020-12-29 10:09 UTC by alexey-zakharenkov

Many corner cases were properly treated; limitations for the mwm size prediction model applicability were imposed in the form of configuration parameters.

2020-12-29 12:12 UTC, jbenua requested changes

2020-12-29 12:12 UTC, jbenua commented on web/app/borders_api_utils.py
> +    borders_table = main_borders_table
не очень понятно теперь, зачем это переименование

2020-12-29 12:12 UTC, jbenua commented on web/app/borders_api_utils.py
> +    borders_table = main_borders_table
почему бы дальше не использовать просто `main_borders_table`?

2020-12-29 12:12 UTC, jbenua commented on web/app/borders_api_utils.py
> +        borders_table = main_borders_table
не очень понятна необходимость переименования

2020-12-29 12:12 UTC, jbenua commented on web/app/borders_api_utils.py
> +    borders_table = main_borders_table
не очень понятна необходимость переименования

2020-12-29 12:12 UTC, jbenua commented on web/app/borders_api_utils.py
> +        borders_table = main_borders_table
не очень понятна необходимость переименования

2020-12-29 12:12 UTC, jbenua commented on web/app/borders_api_utils.py
> +    borders_table = main_borders_table
не очень понятна необходимость переименования

2020-12-29 12:12 UTC, jbenua commented on web/app/mwm_size_predictor.py
> +    factors = ('urban_pop', 'area', 'city_cnt', 'hamlet_cnt')
зпт в конце тупля желательно сохранять
`('urban_pop', 'area', 'city_cnt', 'hamlet_cnt',)`

2020-12-29 12:12 UTC, jbenua commented on web/app/subregions.py
> +
пустая строка

2020-12-29 12:12 UTC, jbenua commented on web/app/subregions.py
> +    return {subregion_id: {k: subregion_data.get(k) for k in keys}
дефолт тут никакой не надо добавить? или фильтровать по наличию

2020-12-30 12:53 UTC, alexey-zakharenkov commented on web/app/borders_api_utils.py
> +    borders_table = main_borders_table
Убрал имя `main_borders_table`. Сделал как в других модулях, где основная таблица импортируется под именем `borders_table`. Вместо этого в единственном методе fetch_borders, где таблица может быть другая, дал ей имя `a_borders_table` (типа с артиклем _a_).

2020-12-30 12:54 UTC, alexey-zakharenkov commented on web/app/mwm_size_predictor.py
> +    factors = ('urban_pop', 'area', 'city_cnt', 'hamlet_cnt')
ок

2020-12-30 12:56 UTC, alexey-zakharenkov commented on web/app/subregions.py
> +
Думал скомбинировать импорт имён таблиц и отделить от имени прочего параметра.
Убрал пустую строку и отсортировал параметры по алфавиту.

2020-12-30 12:57 UTC, alexey-zakharenkov commented on web/app/subregions.py
> +    return {subregion_id: {k: subregion_data.get(k) for k in keys}
Добавил фильтр по наличию

2020-12-30 14:11 UTC, jbenua requested changes

2020-12-30 14:11 UTC, jbenua commented on web/app/countries_structure.py
>              SELECT osm_id, name
а зачем здесь, кстати, выгребается name, если он потом не используется?

2020-12-30 14:11 UTC, jbenua commented on web/app/borders_api.py
> +
предлагаю вынести в отдельный метод типа `prepare_search_token` / `prepare_search_param` или как-нибудь так
и вообще там может быть регуляркой реплейсить, будет лаконичнее

2020-12-30 15:44 UTC, alexey-zakharenkov commented on web/app/countries_structure.py
>              SELECT osm_id, name
убрал

2020-12-30 15:46 UTC, alexey-zakharenkov commented on web/app/borders_api.py
> +
в метод вынес, но как переделать логику if-else на регулярках, не придумал.

2020-12-30 18:49 UTC, merged